### ISSUE TITLE
"NameError: name 'Target' is not defined"

### ISSUE THREAD

**Issue by Av1zi** [Amp63/pyre#2]
first of all, I'm so sorry that I'm wasting your time and opening this many tickets but I keep getting this error for some reason, even tho i have copied from read.me example
![image](https://github.com/Amp63/pyre/assets/137340642/653d1be3-0aea-457a-8e4b-eb31c82d672c)
![image](https://github.com/Amp63/pyre/assets/137340642/42bff5e2-287e-4c41-a982-7b160444552e)

**Comment by Amp63** [comment]
One thing that could be going wrong is that the module isn't updated to 0.4.5, so try running `pip install dfpyre --upgrade` to try updating it.

**Comment by Av1zi** [comment]
dont think its that
btw i use pycharm if it matters...
![image](https://github.com/Amp63/pyre/assets/137340642/69318e63-c256-41f6-bb0e-169dd807baac)

**Comment by Amp63** [comment]
Yeah it looks like you're still on version 0.4.3 which doesn't have the Target object. You need to update to 0.4.5

**Comment by Av1zi** [comment]
ooh my bad, I'm so fucking dumb so sorry about all the tickets!

**Comment by Amp63** [comment]
No problem, glad I could help
