### ISSUE TITLE
Bracket-requiring codeblocks are broken

### ISSUE THREAD

**Issue by ryanbuck182** [Amp63/pyre#3]
Using any bracket-requiring codeblock requires you to send an index with it to work. This is because every bracket-requiring codeblock calls _openbracket, which has line 338 in pyre.py:

`self._add_codeblock(bracket, index+1)`

This treats index as if it's always an integer even though it can be None instead. To fix this you could replace line 338 with:

`self._add_codeblock(bracket, index + 1 if (index is not None) else len(self.codeblocks) - 1)`

**Comment by Amp63** [comment]
Yeah, I actually fixed this one a while ago but forgot to publish a new release. I'll publish a new one as soon as I can. Thanks for letting me know

**Comment by Amp63** [comment]
Fixed in 0.6.2. Thanks!
