### ISSUE TITLE
Parameter default values are not automatically converted into df types

### ISSUE THREAD

**Issue by ryanbuck182** [Amp63/pyre#6]
This is very minor but if you set a parameter's default value like so:

`p = parameter('parameter name', ParameterType.NUMBER, optional=True, default_value=1)`

it won't work because the default value argument won't be automatically converted into a num, so you'd have to do:

`p = parameter('parameter name', ParameterType.NUMBER, optional=True, default_value=num(1))`

**Comment by Amp63** [comment]
Fixed. Thanks!
