### ISSUE TITLE
Code block name "ScoreDefFormat" not recognized

### ISSUE THREAD

**Issue by ryanbuck182** [Amp63/pyre#7]
The player action codeblock, "Set Scoreboard Default Number Format," written on the sign in-game as "ScoreDefFormat," doesn't seem to be recognized. I made a template with it in-game and checked the json for it, and I can confirm that it's called "ScoreDefFormat" there as well. The codeblock is also broken, probably because it's not being recognized; it spawns without stone after it, preventing following codeblocks from being placed, and it's also missing the codeblock tag it's supposed to have. This differs from other codeblocks, where they still spawn with their codeblock tags, they're just set to their default value. (Also thanks for being active and fixing the bugs I've been finding, I really appreciate it.)

**Comment by Amp63** [comment]
Fixed in 0.7.0 with the inclusion of the full actiondump. Thanks!
