### ISSUE TITLE
Repeat block doesn't work unless you send an argument

### ISSUE THREAD

**Issue by ryanbuck182** [Amp63/pyre#8]
Most of the time, you're going to be sending an argument to a repeat block anyway, but in the case of something like: 

```
t.repeat('Forever')
t.bracket(
    # code
)
```

it won't work, you'd have to do:

```
t.repeat('Forever', item('air'))
t.bracket(
    # code
)
```

**Comment by Amp63** [comment]
Should be working in 0.7.1, lmk if it's still not working

**Comment by ryanbuck182** [comment]
Thanks! Seems like it's working to me :)
